config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"

  resources :items, only: [:index, :new, :create, :show, :edit, :update] do
    collection do 
      get 'post','search','modal'
    end
  end

  resources :profiles, only: [:show, :new, :edit, :create, :update] do
    member do 
      get 'show_user'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'トップス' },
    { id: 3, name: 'ジャケット/アウター' },
    { id: 4, name: 'パンツ' },
    { id: 5, name: '靴' },
    { id: 6, name: 'バッグ' },
    { id: 7, name: 'スーツ' },
    { id: 8, name: '帽子' },
    { id: 9, name: 'アクセサリー' },
    { id: 10, name: '小物' },
    { id: 11, name: 'コーディネート'}
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :profile
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  with_options presence: true do
    validates :title
    validates :image
    validates :category_id
  end

  validates :category_id, numericality: { other_than: 1 }

  def self.search(search)
    if search != ""
      Item.where('title LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_item_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_item_tag
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :items

  with_options presence: true do
    validates :name, length: { maximum: 20 }
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :tag_maps
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :item
  belongs_to :tag

  validates :item_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
             
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,20}+\z/i.freeze
  validates :password, presence: true
  validates :password, format: { with: VALID_PASSWORD_REGEX }, allow_blank: true

  has_many :items
  has_one :profile, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:index]

  def index
    @items = Item.all
    @tag_lists = Tag.all
  end

  def new
    @tag_list = Tag.all
    @items = Item.all 
    @item = current_user.items.new 
  end

  def edit 
    @item_tags = @item.tags.pluck(:tag_name).join(" ") 
  end

  def post
    @items = Item.all
  end

  def create
    @item = Item.new(item_params)
    tag_list = params[:item][:tag_name].split(nil)  
    if @item.save
      @item.save_tag(tag_list)
      redirect_to post_items_path
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    tag_list = params[:item][:tag_name].split(nil)  
    if @item.update(item_params)
      @item.save_tag(tag_list)
      redirect_to root_path, notice: "投稿情報の更新が完了しました" 
    else
      render :edit
    end
  end

  def show
    @item_tags = @item.tags 
    @profile = @item.profile
  end

  def search
    @items = Item.search(params[:keyword])
  end

  def modal
  end

  private

  def item_params
    params.require(:item).permit(:image, :title, :category_id, :information).merge(user_id: current_user.id, profile_id: current_user.profile.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :find_profile, only: [:show, :edit, :update, :show_user]

  def show
    @items  = current_user.items
    @image  = @profile.image
  end

  def show_user
    @image  = @profile.image
    @items  = @profile.items
  end

  def new 
    @profile = Profile.new
  end 
  
  def edit 
  end

  def create
    @profile.user = current_user
    if @profile.save
      redirect_to root_path, notice: "プロフィール情報の登録が完了しました" 
    else
      render :new
    end
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      redirect_to root_path, notice: "プロフィール情報の更新が完了しました" 
    else
      render :edit
    end
  end

  def destroy
  end

  private 

  def find_profile
    @profile = Profile.find(params[:id])
  end
  
  def profile_params
    params.require(:profile).permit(
      :name, :self_introduction, :image, :id
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<div class="items-contents">

  <div class="items-main">
    <h2 class="items-title">投稿情報を編集</h2>
    <%= form_with(model: @item, local: true) do |f| %>
    
      <%= render 'shared/error_messages', model: f.object %>
  
      <div class="image-upload">
        <div class="weight-bold-text">
          投稿画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
        <%# 投稿写真選択 %>
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"preview-image" %>
        </div>
      </div>
      <div id="image-list"></div>
      
      <div class="new-items">
        <div class="weight-bold-text">
          タイトル
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field  :title, class:"items-text", id:"item-name", placeholder:"(例)アイテムやコーデの名前など", maxlength:"40" %>
  
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        </div>
  
        <div class="weight-bold-text">
          タグ<br>
          (半角スペースを入力することでタグをつけることができます)
        </div>
        <%= f.text_field  :tag_name, class:"items-text", id:"item-name", placeholder:"(例)ストリート系 きれいめ モード など", maxlength:"40", value: @item_tags%>
  
        <div class="items-explain">
          <div class="weight-bold-text">
            アイテム、コーデについて
          </div>
          <%= f.text_area :information, size: "20x5", class:"items-text", id:"item-info", placeholder:"(例)どんなアイテムか？、どんなコーデか？", maxlength:"1000" %>
        </div>
    </div>
  
    <div class="btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>

<% unless user_signed_in? %>
  <div class='title-contents'>
    <h2 class='site-title'>
      Old fashion
    </h2>
    <p class='what-site'>古着専用の写真投稿サイト</p>
  </div>
<% else %>
  <% @items.each do |item| %>
  <div class='item-contents'>
    <div class = 'timeline'>
      <div class = 'timeline-column'>
        <div class = 'image-field'>
          <%= image_tag(item.image , class:'timeline-image') %>
        </div>
  
        <div class = 'item-body'>
          <div class = 'item-body-contents'>
  
            <div class= 'item-profile'>
              <div class= 'item-profile-icon'>
              <% if item.profile.image.present? %>
              <%= link_to image_tag(item.profile.image, class:'mini-image') , "/profiles/#{item.profile.id}/show_user" %>
              <% else %>
              <span class= 'image-text' >NO IMAGE</span>
              <% end %>
              </div>
              <div class= 'item-profile-name'>
                <p class= 'mini-name'>
                <%= item.profile.name %>
                </p>
              </div>
              <% if item.user_id == current_user.id %>
                <div class = 'item-option'>
                    <div class = 'item-option-btn' >
                      <%= link_to('#', class: 'option-btn') do%>
                      <%= image_tag 'gear_icon.png' ,class: 'item-btn-icon'%>
                      <% end %>
                    </div >
                </div>
              <% end %>
            </div>
            
            <div class = 'item-detail'>
              <p class = 'detail-title'>Title</p>
              <p class = 'detail-message'>
              <%= item.title %>
              </p>
            </div>
  
            <div class = 'item-detail'>
              <p class = 'detail-title'>Category</p>
              <p class = 'detail-message'>
              <%= item.category.name %>
              </p>
            </div>
  
            <div class = 'item-detail-tag'>
              <p class = 'detail-title-tag'>Tag</p>
              <p class = 'detail-message-tag'>
              <% unless item.tags.empty? %>
              <% item.tags.each do |tag| %>
                #<%=tag.tag_name %>
              <%end %>
              <% else %>
              未記入
              <% end %>
              </p>
            </div>
  
            <div class = 'item-information'>
              <p class = 'detail-title'>Information</p>
              <p class = 'detail-message'>
              <% unless item.information.empty? %>
              <%= item.information %>
              <% else %>
              未記入
              <% end %>
              </p>
            </div>
  
          </div>
        </div>
        
      </div>
    </div>
  </div>
  <% end %>
<% end %>

<%= render "shared/post_btn" %>


<%# <%= render "shared/footer" %> 

app/views/items/new.html.erb
<div class="items-contents">

  <div class="items-main">
    <h2 class="items-title">投稿情報を入力</h2>
    <%= form_with(model: @item, local: true) do |f| %>

    
    <%= render 'shared/error_messages', model: f.object %>

    <div class="image-upload">
      <div class="weight-bold-text">
        投稿画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
      <%# 投稿写真選択 %>
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"preview-image" %>
      </div>
    </div>
    <div id="image-list"></div>
    
    
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field  :title, class:"items-text", id:"item-name", placeholder:"アイテムやコーデの名前など", maxlength:"40" %>

      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <div class="weight-bold-text">
        ブランド名
      </div>
      <%= f.text_field  :brand, class:"items-text", id:"item-name", placeholder:"ブランド名", maxlength:"40" %>

      <div class="items-explain">
        <div class="weight-bold-text">
          アイテム、コーデについて
        </div>
        <%= f.text_area :information, size: "20x5", class:"items-text", id:"item-info", placeholder:"どんなアイテムか？、どんなコーデか？", maxlength:"1000" %>
      </div>
    </div>
  
    <div class="btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>

app/views/items/post.html.erb
<%= render "shared/header" %>

<div class='item-contents'>
  <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>

  <div class = contents-row >
    <ul class='item-lists'>
      <% @items.each do |item| %>
            <li class='list'>
              <%= link_to item_path(item.id), method: :get do %>
                 <%= image_tag(item.image, class:"post-image") %>
               <% end %>
            </li>
      <% end %>
    </ul>
  </div>

  <%= render "shared/post_btn" %>
</div>

app/views/items/search.html.erb
<%= render "shared/header" %>

<div class='item-contents'>
  <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>

  <div class = contents-row >
    <ul class='item-lists'>
      <% @items.each do |item| %>
            <li class='list'>
                <%= link_to item_path(item.id), method: :get do %>
                  <%= image_tag(item.image, class:"post-image") %>
                <% end %>
            </li>
      <% end %>
    </ul>
  </div>

  <%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'camera_icon.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  <% end %>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<div class='item-contents'>
  <div class = 'details'>

    <div class= 'details-column' >

      <div class= 'image-field'>
        <%= image_tag(@item.image, class:"image-content") %>
      </div>

      <div class = 'item-body'>
        <div class = 'item-body-contents'>

          <div class= 'item-profile'>
            <div class= 'item-profile-icon'>
              <% if @profile.image.present? %>
              <%= link_to image_tag(@profile.image, class:"mini-image"), "/profiles/#{@profile.id}/show_user" %>
              <% else %>
              <span class= 'image-text' >NO IMAGE</span>
              <% end %>
            </div>
            <div class= 'item-profile-name'>
              <p class= 'mini-name'>
              <%= @profile.name%>
              </p>
            </div>
            
            <% if @item.user_id == current_user.id %>
              <div class = 'item-option'>
                  <div class = 'item-option-btn' >
                    <%= link_to(edit_item_path, class: 'option-btn') do %>
                    <%= image_tag 'gear_icon.png' ,class: 'item-btn-icon' %>
                    <% end %>
                  </div >
              </div>
            <% end %>

          </div>
          
          <div class = 'item-detail'>
            <p class = 'detail-title'>Title</p>
            <p class = 'detail-message'>
            <%= @item.title %>
            </p>
          </div>

          <div class = 'item-detail'>
            <p class = 'detail-title'>Category</p>
            <p class = 'detail-message'>
            <%= @item.category.name %>
            </p>
          </div>

          <div class = 'item-detail-tag'>
            <p class = 'detail-title-tag'>Tag</p>
            <p class = 'detail-message-tag'>
            <% unless @item_tags.empty? %>
            <%@item_tags.each do |tag| %>
              #<%=tag.tag_name%>
            <%end%>
            <% else %>
            未記入
            <% end %>
            </p>
          </div>

          <div class = 'item-information'>
            <p class = 'detail-title'>Information</p>
            <p class = 'detail-message'>
            <% unless @item.information.empty? %>
            <%= @item.information %>
            <% else %>
            未記入
            <% end %>
            </p>
          </div>

        </div>
      </div>
    </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OldFashion</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  <%= javascript_pack_tag 'application'%>
  </body>
</html>

app/views/profiles/edit.html.erb
<div class="items-profile-contents">

  <div class="items-main">
    <h2 class="items-title"> アカウント情報編集</h2>
    <%= form_with(model: @profile, local: true) do |f| %>

    
    <%= render 'shared/error_messages', model: f.object %>

    <div class="image-upload">
      <div class="weight-bold-text">
        プロフィール画像
      </div>
      <div class="click-upload">
      <%# 投稿写真選択 %>
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"preview-image" %>
      </div>
    </div>
    <div id="image-list"></div>
    
    
    <div class="new-items">
      <div class="weight-bold-text">
        名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"input-default", id:"nickname", placeholder:"例) 山田太郎" %>

      <div class="items-explain">
        <div class="weight-bold-text">
          自己紹介
        </div>
        <%= f.text_area :self_introduction, size: "20x5", class:"user-profile-box", id:"item-info", maxlength:"1000" %>
      </div>
    </div>
  
    <div class="btn-contents">
      <%= f.submit "変更する" ,class:"edit-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>

app/views/profiles/new.html.erb
<div class="items-profile-contents">

  <div class="items-main">
    <h2 class="items-title"> アカウント情報作成</h2>
    <%= form_with(model: @profile, local: true) do |f| %>

    
    <%= render 'shared/error_messages', model: f.object %>

    <div class="image-upload">
      <div class="weight-bold-text">
        プロフィール画像
      </div>
      <div class="click-upload">
      <%# 投稿写真選択 %>
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"preview-image" %>
      </div>
    </div>
    <div id="image-list"></div>
    
    
    <div class="new-items">
      <div class="weight-bold-text">
        名前
      </div>
      <%= f.text_area :name, class:"input-default", id:"nickname", placeholder:"例) 山田太郎" %>

      <div class="items-explain">
        <div class="weight-bold-text">
          自己紹介
        </div>
        <%= f.text_area :self_introduction, size: "20x5", class:"user-profile-box", id:"item-info", maxlength:"1000" %>
      </div>
    </div>
  
    <div class="btn-contents">
      <%= f.submit "変更する" ,class:"edit-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>

app/views/profiles/show.html.erb
<%= render "shared/header" %>

<div class = contents >
  <div class = user-contents>
    <div class = user-profile >
      <div class = user-profile-left >
        <div class = profile-icon>
        <% if @image.present? %>
        <%= image_tag(@image, :size => '180x180', class:"profile-image") %>
        <% else %>
        <span class= 'image-text' >NO IMAGE</span>
        <% end %>
        </div>
      </div>
      <div class = user-profile-right>
        <div class = profile-contents-top>
          <div class = user-name >
            <%= @profile.name %>
          </div>
          <div class = profile-option>
            <div class = profile-option-btn >
            <%= link_to(edit_profile_path, class: 'option-btn') do %>
            <%= image_tag 'gear_icon.png' ,class: "profile-btn-icon" %>
            <% end %>
            </div >
          </div>
        </div>
        <div class = profile-contents-row >
          <div class = profile-bio >
          <%# ここに自己紹介文 %>
          <%= @profile.self_introduction%>
          </div>
        </div>
      </div>
    </div>
    <div class = user-post-contents >
      <ul class='item-lists'>
        <% @items.each do |item| %>
              <li class='list'>
                  <%= link_to item_path(item.id), method: :get do %>
                    <%= image_tag(item.image, class:"post-image") %>
                  <% end %>
              </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/profiles/show_user.html.erb
<%= render "shared/header" %>

<div class = contents >
  <div class = user-contents>
    <div class = user-profile >
      <div class = user-profile-left >
        <div class = profile-icon>
        <% if @image.present? %>
        <%= image_tag(@image, class:"profile-image") %>
        <% else %>
        <span class= 'image-text' >NO IMAGE</span>
        <% end %>
        </div>
      </div>
      <div class = user-profile-right>
        <div class = profile-contents-top>
          <div class = user-name >
            <%= @profile.name %>
          </div>
          
          <% if @profile.user_id == current_user.id %>
            <div class = profile-option>
              <div class = profile-option-btn >
              <%= link_to(edit_profile_path, class: 'option-btn') do %>
              <%= image_tag 'gear_icon.png' ,class: "profile-btn-icon" %>
              <% end %>
              </div >
            </div>
          <% end %>
          
          
        </div>
        <div class = profile-contents-row >
          <div class = profile-bio >
          <%# ここに自己紹介文 %>
          <%= @profile.self_introduction%>
          </div>
        </div>
      </div>
    </div>
    <div class = user-post-contents >
      <ul class='item-lists'>
        <% @items.each do |item| %>
              <li class='list'>
                  <%= link_to item_path(item.id), method: :get do %>
                    <%= image_tag(item.image, class:"post-image") %>
                  <% end %>
              </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <%= link_to image_tag("Old_01.png", class:"logo-white"), "#" %>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='application-title'>
   <%= link_to image_tag("Old_01.png", class:"title-icon"), root_path %>
  </div>
  <div class= 'nav'>
    <ul class='lists-left'>
      <li><%= link_to image_tag("Old_03.png", class:"nav-icon"), post_items_path %></li>
    </ul>
    <ul class= 'lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to image_tag("Old_06.png", class:"nav-icon"), destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"}%></li>
        <% unless current_user.profile.nil? %>
          <li><%= link_to image_tag("Old_07.png", class:"nav-icon"), "/profiles/#{current_user.profile.id}" %></li>
        <% else %>
          <li><%= link_to image_tag("Old_07.png", class:"nav-icon"), new_profile_path %></li>
        <% end %>
      <% else %>
        <li><%= link_to image_tag("Old_04.png", class:"nav-icon"), new_user_session_path %></li>
        <li><%= link_to image_tag("Old_05.png", class:"nav-icon"), new_user_registration_path %></li>
      <% end %>
    </ul>
</header>

app/views/shared/_post_btn.html.erb
<%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'camera_icon.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>